[project]
name = "scd"
version = "0.1.0"
description = "The Sickle Cell Disease"
readme = "README.md"
authors = [
    { name = "James Rowa", email = "j*****@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
scd = "scd:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
